apiVersion: v1
kind: Service
metadata:
  labels:
    name: lapin
  name: lapin
  namespace: openproject
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: lapin
