apiVersion: v1
kind: Service
metadata:
  labels:
    app_role: proxy
  name: proxy
  namespace: openproject
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app_role: proxy
