---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: openproject
  labels:
    app_role: web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app_role: web
