apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openproject-ingress
  namespace: openproject
spec:
  rules:
  - host: op.jaep.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lapin
            port:
              number: 80
