apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app_role: opdata
  name: opdata
  namespace: openproject
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
